name: build

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

  pull_request:
  workflow_dispatch:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: dart-lang/setup-dart@v1
      - name: checkout
        uses: actions/checkout@v4
      - name: format check
        run: make format-check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: dart-lang/setup-dart@v1
      - name: checkout
        uses: actions/checkout@v4
      - name: lint
        run: make lint

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: dart-lang/setup-dart@v1
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: make build

  pub-dry-run:
    name: Publish Dry Run
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: dart-lang/setup-dart@v1
      - name: checkout
        uses: actions/checkout@v4
      - name: publish dry run
        run: make publish-test

  test-dart:
    name: Test
    needs: [ lint, format, pub-dry-run, build ]
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: dart-lang/setup-dart@v1
      - name: setup lcov
        run: sudo apt-get install lcov
      - name: checkout
        uses: actions/checkout@v4
      - name: check coverage
        run: make coverage-check

  # https://dart.dev/tools/pub/automated-publishing
  release:
    name: Release
    permissions:
      id-token: write
    if: startsWith(github.ref, 'refs/tags/')
    needs: [ test-dart ]
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: dart-lang/setup-dart@v1
      - name: checkout
        uses: actions/checkout@v4
      - name: check tag version
        run: dart scripts/check_release_version.dart ${{ github.ref }}
      - name: publish
        run: make publish
